<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>RhinoPrefabGeometryPlugin</AssemblyName>
    <RootNamespace>RhinoPrefabGeometryPlugin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="RhinoCommon">
      <HintPath>$(ProgramFiles)\Rhino 8\System\RhinoCommon.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>

